---
title: 'Blog Post #1'
author: "Ellie Grueskin"
date: "2022-09-10"
output:
  pdf_document: default
  html_document: default
slug: []
categories: []
tags: []
---

In this blog post, I focus on the third extension project: an extension of the
swing state map. The plot below shows each state's four-year
difference in Republican vote margin, starting with 1952 because the dataset only started in 1948.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
h<-read.csv("Week1_data/house party vote share by district 1948-2020.csv")
library(tidyverse)
library(usmap)
library(geomtextpath)
```

```{r, message=FALSE}

#Find house averages by state and year
h_avg <- h %>%
  select(raceYear, State,  RepVotes, DemVotes) %>%
# summarize party vote share by state
  group_by(State,raceYear) %>%
# mutate Rep vote margin by state %>%
  summarise(R_votemargin_st = (sum(RepVotes))/
           sum(RepVotes + DemVotes),
D_votemargin_st = (sum(DemVotes))/
sum(RepVotes + DemVotes)) %>%
rename(state = State)

# code na if uncontested
h_avg_2<-h_avg %>%
  group_by(state) %>%
  mutate(uncontested=ifelse(R_votemargin_st==1|D_votemargin_st==1,1,0))%>%
  mutate(R_votemargin_st=na_if(R_votemargin_st, 0),
         R_votemargin_st=na_if(R_votemargin_st, 1)) %>%
  #Lag by 4 years or 2 observations
  mutate(diff = R_votemargin_st-lag(R_votemargin_st,2))


p<-plot_usmap(data=h_avg_2%>% filter(raceYear>1950), regions = "states", values = "diff")+
  facet_wrap(~raceYear) +
  scale_fill_gradient2(low = "blue", mid="white",high = "red", 
  name = "Difference Scale")+labs(title='Difference in GOP 4-yr voteshare margin',
 subtitle='Red=More Republican, Blue=More Democrat, Gray=uncontested/unavailable')+
  theme(legend.position="right")+
  theme_void()

OH01<-h %>% filter(district_id=='OH01')%>%
  mutate(midterm=ifelse(raceYear%%4,0,1),
         Majority=ifelse(R_vote_margin>0,'Republican','Democratic'))
p<-ggplot(data=OH01%>% filter(R_vote_margin>-.5),aes(x=raceYear,y=R_vote_margin, shape=WinnerParty,color=WinnerParty))+geom_point()+
  geom_textvline(label = "Steve Chabot enters", xintercept = 1994, vjust = -.4,linetype=2,color='red',size=3) +  facet_wrap(~RepStatus)+
  scale_color_manual(values=c("Blue","Red"))+
  ggtitle('Republican Vote Margin in OH-01 by Year and \nStatus of Republican Candidate (Challenger or Incumbent)')

p<-ggplot(data=OH01)+geom_line(aes(x=raceYear,y=R_vote_margin,color=factor(midterm),
                                   group=midterm))


                       #i) +

```

Visualization
```{r, message=FALSE}
plot_usmap(data = h_avg%>% filter(raceYear==1988), regions = "states", values = "R_votemargin_st") +
  scale_fill_gradient2(low = "blue", mid="white",high = "red", name = "R Vote Margin, 1988") +
  theme_void()


urlfile="https://raw.githubusercontent.com/kjhealy/fips-codes/master/county_fips_master.csv"

R_2 <- h %>%
    filter(raceYear == 2014) %>%
    select(raceYear, State, district_num, RepVotesMajorPercent, DemVotesMajorPercent) %>%
  # summarize party vote share by district
    group_by(State,district_num) %>%
    summarise(Rep_votes_pct = RepVotesMajorPercent) %>%
# rename district variable name to match shapefile
    rename(DISTRICT = district_num,STATENAME=State)
# require(tidyverse)
# require(ggplot2)
# require(sf)
# # load geographic data
# get_congress_map <- function(cong=114) {
#   tmp_file <- tempfile()
#   tmp_dir <- tempdir()
#   zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts114.zip",cong) 
#   download.file(zp, tmp_file)
#     unzip(zipfile = tmp_file, exdir = tmp_dir)
#     fpath <- paste(tmp_dir, sprintf("districtShapes/districts114.shp",cong), sep = "/")
#     st_read(fpath)
# }
# 
# cd114 <- get_congress_map(114)
# cd114 <- cd114%>%
#             mutate(DISTRICT = as.character(DISTRICT))%>%
#             select(DISTRICT,STATENAME)
# cd114$DISTRICT <- as.numeric(cd114$DISTRICT)
# # join election returns with shapefiles
# cd114 <- cd114 %>% left_join(R_2, by=c("DISTRICT","STATENAME"))
# cd114
#  #%in%c('Arizona','Georgia','Iowa','Pennsylvania'))
# 
# ggplot(data=cd114%>% filter(STATENAME %in% c('New York'))) +
#          geom_sf(aes(fill=Rep_votes_pct),
#           inherit.aes=FALSE,alpha=0.9) +
#   scale_fill_gradient(low = "white", high = "red", limits=c(10,80)) +
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank()) 
# 
# +geom_label(
#     label=rownames(cd114), 
#     nudge_x = 0.25, nudge_y = 0.25, 
#     check_overlap = T
#   )
```

```{r}

# keep uncontested values
h_avg_st<-h_avg %>%
  group_by(state) %>%
  #Lag by 4 years or 2 observations
  mutate(diff = R_votemargin_st-lag(R_votemargin_st,2))


p<-plot_usmap(data=h_avg_st%>% filter(raceYear>1950), regions = "states", values = "diff")+
  facet_wrap(~raceYear) +
  scale_fill_gradient2(low = "blue", mid="white",high = "red", 
  name = "Difference Scale")+labs(title='Difference in GOP 4-yr voteshare margin',
 subtitle='Red=More Republican, Blue=More Democrat, Gray=unavailable')+
  theme(legend.position="right")+
  theme_void()

```

